### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by josemsanchez** [josemsanchez/LST-heat-map#1]
Format text on readme and include a screenshot.

![heat-map](https://user-images.githubusercontent.com/10883694/108610798-72b83a00-73d0-11eb-8ace-bea17d24c179.png)

**Comment by nicomartin8542** [comment]
Hi, I would like to take care of that issue

**Comment by josemsanchez** [comment]
Sure! Go Ahead 👍

**Comment by nicomartin8542** [comment]
Hi,  I sent you a PR to update the README.MD.
